version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./docker/logs/nginx-error.log:/var/log/nginx/error.log"
            - ".:/var/www/html"
        ports:
            - "8000:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        restart: always
        links:
            - php
            - mysqldb
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        links:
            - mysqldb
        volumes:
            - ".:/var/www/html"
    composer:
        image: composer
        volumes:
            - ".:/app"
        command: install --ignore-platform-reqs --no-scripts
    mysqldb:
        image: mysql
        container_name: mysqldb
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./docker/data/db/mysql:/var/lib/mysql"
    node:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
          - NODE_ENV=production
        volumes:
          - ./:/home/node/app
        command: "npm install"